---

- name: Installing node packages
  include_tasks: "packages.yml"

- name: Installing AWS dependencies
  include_tasks: "aws.yml"

- name: Installing container runtime
  include_tasks: "{{ container_runtime }}.yml"

- name: Installing Kubelet Kubeadm Kubectl Critools
  include_tasks: "kubelet.yml"

- name: Installing cloud-init-reporter feature
  include_tasks: "cloud-init-report.yml"
