# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - deploy.yaml

images:
  - name: aws-alb-ingress-controller # amazon/aws-alb-ingress-controller:v2.4.3
    newName: registry.sighup.io/fury/amazon/aws-alb-ingress-controller
    newTag: v2.4.3
