---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - deploy.yaml

images:
  - name: public.ecr.aws/aws-ec2/aws-node-termination-handler
    newName: public.ecr.aws/aws-ec2/aws-node-termination-handler
    newTag: v1.16.2
