---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - deploy.yaml

images:
  - name: aws-node-termination-handler
    newName: registry.sighup.io/fury/aws-ec2/aws-node-termination-handler
    newTag: v1.17.1
